# https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "me"
version = "1.0.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.0-gamma3", features = ["csr", "nightly"] }
